nume_proiect/aplicatie2/urls.py
from django.urls import path

from aplicatie2 import views

app_name = 'companies'

urlpatterns = [
	path('', views.CompanyView.as_view(), name='listare'),
	path('adaugare/', views.CreateCompanyView.as_view(), name='add'),
	path('<int:pk>/update/', views.UpdateCompanyView.as_view(), name='modifica'),
	path('<int:pk>/delete/', views.delete_company, name='sterge'),
	path('<int:pk>/activeaza/', views.activate_company, name='activeaza'),
	path('companies_inactive', views.CompaniesInactiveView.as_view(), name='companies_inactive'),
	path('companies_toate', views.CompaniesAllView.as_view(), name='companies_toate'),
]

nume_proiect/myapi/urls.py
from django.urls import path, include
from rest_framework import routers
from myapi import views

router = routers.DefaultRouter()
router.register('location', views.LocationViewSet)
router.register('companies', views.CompaniesViewSet)

urlpatterns = [
	path('', include(router.urls))
	
]

nume_proiect/nume_proiect/urls.py
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('django.contrib.auth.urls'), {'next_page': '/'}, name='login'),
    path('', LoginView.as_view(template_name='registration/login.html'), name='login'),
    path('locations/', include('aplicatie1.urls')),
    path('companies/', include('aplicatie2.urls')),
    path('profile/', include('userprofile.urls')),
    path('api/', include('myapi.urls'))
    
]

nume_proiect/aplicatie2/models.py
from django.db import models

from aplicatie1.models import Location

company_choices = (('SRL', 'S.R.L.'), ('SA', 'S.A.'))


class Companies(models.Model):
	name = models.CharField(max_length=100)
	website = models.CharField(max_length=50)
	company_type = models.CharField(max_length=10, choices=company_choices)
	active = models.BooleanField(default=1)
	locations = models.ForeignKey(Location, on_delete=models.CASCADE)
	
	def __str__(self):
		return f'{self.name} - {self.company_type}'

nume_proiect/aplicatie2/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic import ListView, CreateView, UpdateView

from aplicatie2.models import Companies


class CompanyView(LoginRequiredMixin, ListView):
	model = Companies
	template_name = 'aplicatie2/Companies_index.html'
	paginate_by = 5
	queryset = model.objects.filter(active=1)
	context_object_name = 'companies'
	
	def get_context_data(self, *args, **kwargs):
		data = super(CompanyView, self).get_context_data(*args, **kwargs)
		# data['companies'] = self.model.objects.filter(active=1)
		return data


class CreateCompanyView(LoginRequiredMixin, CreateView):
	model = Companies
	fields = ['name', 'company_type', 'website', 'active', 'locations']
	template_name = 'aplicatie2/Company_form.html'
	
	def get_success_url(self):
		return reverse('companies:listare')


class UpdateCompanyView(LoginRequiredMixin, UpdateView):
	model = Companies
	fields = ['name', 'company_type', 'website', 'active']
	template_name = 'aplicatie2/Company_form.html'
	
	def get_success_url(self):
		return reverse('companies:listare')


@login_required
def delete_company(request, pk):
	Companies.objects.filter(id=pk).update(active=0)
	return redirect('companies:listare')


@login_required
def activate_company(request, pk):
	Companies.objects.filter(id=pk).update(active=1)
	return redirect('companies:listare')


class CompaniesInactiveView(LoginRequiredMixin, ListView):
	model = Companies
	template_name = 'aplicatie2/Companies_index.html'
	paginate_by = 5
	queryset = model.objects.filter(active=0)
	context_object_name = 'companies'
	
	def get_context_data(self, *args, **kwargs):
		data = super(CompaniesInactiveView, self).get_context_data(*args, **kwargs)
		# data['companies'] = self.model.objects.filter(active=0)
		return data


class CompaniesAllView(LoginRequiredMixin, ListView):
	model = Companies
	template_name = 'aplicatie2/Companies_index.html'
	paginate_by = 5
	queryset = model.objects.filter()
	context_object_name = 'companies'
	
	def get_context_data(self, *args, **kwargs):
		data = super(CompaniesAllView, self).get_context_data(*args, **kwargs)
		# data['companies'] = self.model.objects.filter()
		return data

nume_proiect/templates/aplicatie2/Companies_index.html
{% extends 'base.html' %}
{% block content %}
<a class="btn btn-success" href="{% url 'companies:add' %}">Adauga o companie</a>
<table class="table">
    <thead>
    <tr>
        <th>Index</th>
        <th>Nume Companie</th>
        <th>Website</th>
        <th>Tip Companie</th>
        <th>Stare</th>
    </tr>
    </thead>
    <tbody>
    {% for item in companies %}
    <tr>
        <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
        <td>{{ item.name }}</td>
        <td>{{ item.website }}</td>
        <td>{{ item.company_type }}</td>
        <td>{% if item.active == 1 %}
            <span>Activ</span>
            {% else %}
            <span>Inactiv</span>
            {% endif %}
        </td>
        <td>
            <a href="{% url 'companies:modifica' item.id %}" class="btn btn-info">Modifica</a>
            {% if item.active == 1 %}
            <a href="{% url 'companies:sterge' item.id %}" class="btn btn-danger">Sterge</a>
            {% else %}
            <a href="{% url 'companies:activeaza' item.id %}" class="btn btn-success">Activeaza</a>
            {% endif %}
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
{% if is_paginated %}
<ul class="pagination">
    {% if page_obj.has_previous %}
    <li><a id="id_adaugare" class="btn" href="?page={{ page_obj.previous_page_number }}"><<</a></li>
    {% else %}
    <li class="disabled btn"><span><<</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
    {% if page_obj.number == i %}
    <li class="active btn btn-info"><span>{{ i }}<span class="sr-only">(curent)</span></span></li>
    {% else %}
    <li><a class="btn" href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
    <li><a class="btn" href="?page={{ page_obj.next_page_number }}">>></a></li>
    {% else %}
    <li class="disabled btn"><span>>></span></li>
    {% endif %}
    <span class="align-right">Showing {{ page_obj.start_index }} - {{ page_obj.end_index }} of
            {{ page_obj.paginator.count }}</span>
</ul>
{% endif %}
{% endblock %}

nume_proiect/templates/aplicatie2/Company_form.html
{% extends 'base.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {% for field in form %}
    {{ field.label }} {{ field }} {{ field.errors }}
    {% endfor %}
    <button type="submit" class="btn btn-info">Salveaza</button>
</form>
{% endblock %}